on: release
name: Push Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and Test pipeline-status-plugin
        run: gradle clean build
      - name: Build and Publish pipeline-status-plugin
        run: gradle clean build githubRelease
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}