name: Pull Request Build & Test 

on: 
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build & Test with Gradle
      run: gradle clean build

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install Danger
      run: gem install danger
    
    - name: Execute Danger
      run: bundle exec danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        PARALLEL_DOTS_API_KEY: ${{secrets.PARALLEL_DOTS_API_KEY}}
